# Generated by Django 5.0.2 on 2024-03-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_customer_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(choices=[('ru', 'Россия')], default='ru', max_length=255),
        ),
    ]
