# Generated by Django 5.0.2 on 2024-02-19 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_alt_image_product_alt_thubmnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='alt_thubmnail',
            new_name='alt_thumbnail',
        ),
    ]
