# Generated by Django 5.0.2 on 2024-02-21 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_alt_image_product_image_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail_5',
        ),
    ]
