# Generated by Django 5.0.2 on 2024-02-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_size_alter_product_category_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
