# Generated by Django 5.0.2 on 2024-02-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_size_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image_1',
            new_name='image_main',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail_5',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='products_pr_created_bce1a7_idx'),
        ),
    ]
