# Generated by Django 5.0.2 on 2024-03-02 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
